# Generated by Django 5.0.1 on 2024-02-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
                ('r_des', models.CharField(max_length=50)),
                ('r_img', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
